package generator

import (
    "fmt"
    "os"
    "path/filepath"

    "github.com/hunterkritik-byte/autoline-cli/internal/detector"
)

func Generate(root string, stack detector.Stack) error {
    docker, workflow, precommit := templates(stack)
    files := map[string]string{
        "Dockerfile": docker,
        ".github/workflows/autoline.yml": workflow,
        ".pre-commit-config.yaml": precommit,
    }
    for name, content := range files {
        path := filepath.Join(root, name)
        if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil { return fmt.Errorf("create directory for %s: %w", name, err) }
        if err := os.WriteFile(path, []byte(content), 0o644); err != nil { return fmt.Errorf("write %s: %w", name, err) }
    }
    return nil
}

func templates(s detector.Stack) (string, string, string) {
    docker := fmt.Sprintf("# Generated by AutoLine\nFROM %s AS build\nWORKDIR /app\nCOPY . .\nRUN %s\n\nFROM %s\nWORKDIR /app\nCOPY --from=build /app /app\nCMD [\"sh\", \"-c\", \"%s\"]\n", base(s), s.BuildCommand, runtime(s), s.StartCommand)
    workflow := fmt.Sprintf("name: AutoLine CI\non:\n  push:\n  pull_request:\njobs:\n  build:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4\n      - name: Set up %s\n        uses: %s\n      - name: Build\n        run: %s\n      - name: Docker build\n        run: docker build -t autoline-app .\n", s.Language, setupAction(s), s.BuildCommand)
    precommit := "repos:\n  - repo: https://github.com/pre-commit/pre-commit-hooks\n    rev: v5.0.0\n    hooks:\n      - id: trailing-whitespace\n      - id: end-of-file-fixer\n      - id: check-yaml\n      - id: check-added-large-files\n"
    return docker, workflow, precommit
}

func base(s detector.Stack) string { switch s.Name { case "Node.js": return "node:22-bookworm"; case "Python": return "python:3.13-slim"; case "Go": return "golang:1.24-bookworm"; case "Rust": return "rust:1.88-bookworm"; default: return "alpine:3.22" } }
func runtime(s detector.Stack) string { switch s.Name { case "Node.js": return "node:22-bookworm-slim"; case "Python": return "python:3.13-slim"; case "Go": return "gcr.io/distroless/base-debian12"; case "Rust": return "debian:bookworm-slim"; default: return "alpine:3.22" } }
func setupAction(s detector.Stack) string { switch s.Name { case "Node.js": return "actions/setup-node@v4"; case "Python": return "actions/setup-python@v5"; case "Go": return "actions/setup-go@v5"; case "Rust": return "actions-rust-lang/setup-rust-toolchain@v1"; default: return "actions/checkout@v4" } }
